server:
  port: 8083
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  main:
    web-application-type: reactive
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
        corsConfigurations:
          '[/**]':
            allowedOrigins: '*'
            allowedMethods: '*'
            allowedHeaders: '*'
            exposedHeaders: '*'
      routes:
        - id: registration-service
          uri: lb://REGISTRATION-SERVICE
          predicates:
            - Path=/reg/**
          filters:
            - RewritePath=/registration-service(?<segment>/?.*), $\{segment}

        - id: authentication-service
          uri: lb://AUTHENTICATION-SERVICE
          predicates:
            - Path=/authenticate/**
          filters:
            - RewritePath=/authentication-service(?<segment>/?.*), $\{segment}
        - id: email-service
          uri: lb://EMAIL-SERVICE
          predicates:
            - Path=/mail/**
          filters:
            - RewritePath=/email-service(?<segment>/?.*), $\{segment}
        - id: email-service
          uri: lb://EMAIL-SERVICE
          predicates:
            - Path=/mail/**
          filters:
            - RewritePath=/email-service(?<segment>/?.*), $\{segment}
        - id: product-webapp
          uri: lb://PRODUCT-WEBAPP
          predicates:
            - Path=/mail/**
          filters:
            - RewritePath=/product-webapp(?<segment>/?.*), $\{segment}
        - id: booking-service
          uri: lb://BOOKING-SERVICE
          predicates:
            - Path=/mail/**
          filters:
            - RewritePath=/booking-service(?<segment>/?.*), $\{segment}
        - id: property-owner-service
          uri: lb://PROPERTY-OWNER-SERVICE
          predicates:
            - Path=/mail/**
          filters:
            - RewritePath=/property-owner-service?<segment>/?.*), $\{segment}

#spring:
#  application:
#    name: api-gateway
#  cloud:
#    config:
#      uri: http://localhost:8888
#  config:
#    import: optional:configserver:http://localhost:8888/
#  main:
#    allow-bean-definition-overriding: true
#management:
#  security:
#    enabled: false